# Generated by Django 5.1.6 on 2026-04-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('slot', models.CharField(choices=[('first_breakfast', '1-nonushta'), ('second_breakfast', '2-nonushta'), ('lunch', 'Tushlik'), ('buffet', 'Bufet mahsulotlari'), ('dinner', 'Kechki ovqat')], max_length=32, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('ml', 'Millilitr')], default='g', max_length=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('winter', 'Qish'), ('spring', 'Bahor'), ('summer', 'Yoz'), ('autumn', 'Kuz')], max_length=100)),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-year', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.diet')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MenuDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('people_count', models.PositiveIntegerField(default=1)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.diet')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.organization')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.season')),
            ],
            options={
                'ordering': ('-date', 'organization__name'),
            },
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dish')),
                ('mealtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.mealtime')),
                ('menu_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='menu.menuday')),
            ],
            options={
                'ordering': ('mealtime__order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.product')),
            ],
        ),
    ]
