# Generated by Django 5.1.6 on 2026-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_organization_organization_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
