# Generated by Django 5.1.6 on 2026-05-09 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ('code',), 'verbose_name': 'Parhez', 'verbose_name_plural': 'Parhezlar'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('name',), 'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'verbose_name': 'Taom tarkibi', 'verbose_name_plural': 'Taom tarkibi'},
        ),
        migrations.AlterModelOptions(
            name='mealtime',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Ovqatlanish vaqti', 'verbose_name_plural': 'Ovqatlanish vaqtlari'},
        ),
        migrations.AlterModelOptions(
            name='menuday',
            options={'ordering': ('-date', 'organization__name'), 'verbose_name': 'Menyu kuni', 'verbose_name_plural': 'Menyu kunlari'},
        ),
        migrations.AlterModelOptions(
            name='menuentry',
            options={'ordering': ('mealtime__order', 'id'), 'verbose_name': 'Menyu yozuvi', 'verbose_name_plural': 'Menyu yozuvlari'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Tashkilot', 'verbose_name_plural': 'Tashkilotlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-year', 'name'), 'verbose_name': 'Mavsum', 'verbose_name_plural': 'Mavsumlar'},
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='menu.organization')),
            ],
            options={
                'verbose_name': 'AI menyu tavsiyasi',
                'verbose_name_plural': 'AI menyu tavsiyalari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('excel', 'Excel import'), ('price_url', 'Internet narx'), ('price_ai', 'AI narx'), ('menu_ai', 'AI menyu')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Bajarildi'), ('failed', 'Xatolik')], default='pending', max_length=16)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='menu.organization')),
            ],
            options={
                'verbose_name': 'Import vazifasi',
                'verbose_name_plural': 'Import vazifalari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MenuAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('danger', 'Xavf')], default='warning', max_length=16)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='menu.menuday')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_alerts', to='menu.organization')),
            ],
            options={
                'verbose_name': 'Menyu ogohlantirishi',
                'verbose_name_plural': 'Menyu ogohlantirishlari',
                'ordering': ('is_resolved', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Direktor'), ('cook', 'Oshpaz'), ('accountant', 'Hisobchi'), ('viewer', 'Kuzatuvchi')], default='viewer', max_length=32)),
                ('can_manage_menu', models.BooleanField(default=False)),
                ('can_manage_prices', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='menu.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tashkilot a'zosi",
                'verbose_name_plural': "Tashkilot a'zolari",
                'ordering': ('organization__name', 'user__username'),
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_type', models.CharField(choices=[('manual', "Qo'lda"), ('excel', 'Excel'), ('url', 'Internet jadval'), ('ai', 'AI internet qidiruv')], default='manual', max_length=16)),
                ('source_label', models.CharField(blank=True, max_length=300)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='menu.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='menu.product')),
            ],
            options={
                'verbose_name': 'Narx tarixi',
                'verbose_name_plural': 'Narx tarixi',
                'ordering': ('-created_at', 'product__name'),
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_subscription', to='menu.organization')),
            ],
            options={
                'verbose_name': 'Telegram sozlama',
                'verbose_name_plural': 'Telegram sozlamalari',
            },
        ),
    ]
