# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_diet_options_alter_dish_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("export", "Eksport"),
                            ("import", "Import"),
                            ("price", "Narx"),
                            ("alert", "Ogohlantirish"),
                            ("telegram", "Telegram"),
                            ("login", "Kirish"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="menu.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dietology_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit yozuvi",
                "verbose_name_plural": "Audit yozuvlari",
                "ordering": ("-created_at",),
            },
        ),
    ]
