# Generated by Django 4.2.29 on 2026-06-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscription',
            name='organization',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='TelegramSubscription',
        ),
    ]
