# Generated by Django 4.2.29 on 2026-06-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_telegramsubscription_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='job_type',
            field=models.CharField(choices=[('excel', 'Excel import'), ('price_url', 'Internet narx'), ('price_ai', 'AI narx')], max_length=24),
        ),
    ]
