from django.urls import path
from .views import (
    AllMenuWordExportView,
    AISuggestionView,
    AlertBuildView,
    HomeView,
    LatestMenuWordExportView,
    MenuUploadView,
    NewsListView,
    OrganizationListView,
    OrganizationLoginView,
    PriceUpdateView,
    ProfileView,
    TelegramWebhookSetupView,
    TelegramWebhookStatusView,
    TelegramWebhookView,
    TelegramSettingsView,
    health_check,
    logout_view,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("organizations/", OrganizationListView.as_view(), name="organization_list"),
    path("news/", NewsListView.as_view(), name="news"),
    path("login/", OrganizationLoginView.as_view(), name="login"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/export-word/", LatestMenuWordExportView.as_view(), name="profile_export_word"),
    path("profile/export-all-word/", AllMenuWordExportView.as_view(), name="profile_export_all_word"),
    path("profile/update-prices/", PriceUpdateView.as_view(), name="profile_update_prices"),
    path("profile/import-menu/", MenuUploadView.as_view(), name="profile_import_menu"),
    path("profile/build-alerts/", AlertBuildView.as_view(), name="profile_build_alerts"),
    path("profile/ai-suggestion/", AISuggestionView.as_view(), name="profile_ai_suggestion"),
    path("profile/telegram/", TelegramSettingsView.as_view(), name="profile_telegram"),
    path("telegram/webhook/", TelegramWebhookView.as_view(), name="telegram_webhook"),
    path("telegram/setup/", TelegramWebhookSetupView.as_view(), name="telegram_setup"),
    path("telegram/status/", TelegramWebhookStatusView.as_view(), name="telegram_status"),
    path("healthz", health_check, name="health_check"),
    path("logout/", logout_view, name="logout"),
]
