from django.urls import path
from .views import (
    AIAgentView,
    AllMenuWordExportView,
    AlertBuildView,
    AllMenuExcelExportView,
    HomeView,
    LatestMenuWordExportView,
    MenuUploadPreviewView,
    MenuUploadView,
    NewsListView,
    OrganizationListView,
    OrganizationLoginView,
    PriceUpdateView,
    ProfileView,
    health_check,
    logout_view,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("organizations/", OrganizationListView.as_view(), name="organization_list"),
    path("news/", NewsListView.as_view(), name="news"),
    path("login/", OrganizationLoginView.as_view(), name="login"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/export-word/", LatestMenuWordExportView.as_view(), name="profile_export_word"),
    path("profile/export-all-word/", AllMenuWordExportView.as_view(), name="profile_export_all_word"),
    path("profile/export-all-excel/", AllMenuExcelExportView.as_view(), name="profile_export_all_excel"),
    path("profile/update-prices/", PriceUpdateView.as_view(), name="profile_update_prices"),
    path("profile/import-preview/", MenuUploadPreviewView.as_view(), name="profile_import_preview"),
    path("profile/import-menu/", MenuUploadView.as_view(), name="profile_import_menu"),
    path("profile/build-alerts/", AlertBuildView.as_view(), name="profile_build_alerts"),
    path("profile/ai-agent/", AIAgentView.as_view(), name="profile_ai_agent"),
    path("healthz", health_check, name="health_check"),
    path("logout/", logout_view, name="logout"),
]
